name: generate-pacman-graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: generate-pacman-svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MohamedHamed-bot
          template: classic
          base: ""
          config_display: pacman
          plugin_isocalendar: yes
          filename: pacman-contributions.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pacman-contributions.svg
          git commit -m "Update pacman graph" || exit 0
          git push
