name: generate-pacman-graph

on:
  schedule:
    - cron: "0 0 * * *" # بيشتغل كل يوم الساعة 12 بالليل
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate-pacman-svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MohamedHamed-bot
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # هنا بنحدد إن الشكل يكون Pacman
          config_display: pacman 
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
