name: generate-pacman-graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: generate-pacman-svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }}
          user: MohamedHamed-bot
          template: classic
          base: ""
          config_display: pacman
          plugin_isocalendar: yes
          filename: pacman-contributions.svg

      - name: Push to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update pacman-contributions.svg"
          file_pattern: 'pacman-contributions.svg'
